### ISSUE TITLE
docker image push command

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/ak-cli#167]
`docker push [OPTIONS] NAME[:TAG]`

**Comment by thilakarajk** [comment]
@arshadkazmi42 I'll work on this issue.

**Comment by thilakarajk** [comment]
In order to complete the docker push command, docker login command is required. 

So Shall I create a new issue for `docker login [OPTIONS] [SERVER]` ?

**Comment by arshadkazmi42** [comment]
sure go ahead. Can you also create a issue for that
