### ISSUE TITLE
docker registry login command

### ISSUE THREAD

**Issue by thilakarajk** [arshadkazmi42/ak-cli#171]
`docker login [OPTIONS] [SERVER]`

**Comment by thilakarajk** [comment]
@arshadkazmi42 Is there any syntax, which you are maintaining for denoting Optional argument?

In this command, both `[OPTIONS]` and `[SERVER]` are Optional arguments.

**Comment by arshadkazmi42** [comment]
@thilakarajk No, we don't have any thing specific currently. 
Feel free to define it. I was also planning on setup a document about these standardization we are following. We can include optional thing also in that

**Comment by thilakarajk** [comment]
Great. As of now, the arguments are enclosed by `{{ARGUMENT}}`. I'm planning to use `[[OPTIONAL_ARGUMENT]]` for an optional argument. Any suggestions?

**Comment by arshadkazmi42** [comment]
Sounds good.
