### ISSUE TITLE
Remove badges from README.md

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/ak-cli#196]
Remove sponsor badges `Buy Me a Coffee` and `Patron` from readme
also remove this line `Please consider donating, if you like my work`

**Comment by SwatiAF** [comment]
Hey, can you assign this issue to me? I'm new to open source, so I'll try my best.

**Comment by arshadkazmi42** [comment]
> Hey, can you assign this issue to me? I'm new to open source, so I'll try my best.

@SwatiAF I have assigned the issue to you.
You can go ahead send a PR with the changes

**Comment by Safirangi** [comment]
Sorry I claimed earlier with my other account, I wasn't aware..
