### ISSUE TITLE
 Create PULL_REQUEST_TEMPLATE

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/ak-cli#20]
Create a file with this name
`PULL_REQUEST_TEMPLATE.md` in the repo and add this in it
`Fixes #`

**Comment by respectmyauthori-tah** [comment]
May I help with this?

**Comment by arshadkazmi42** [comment]
@respectmyauthori-tah Yes. Go ahead.
Let me know, if you need any other information.
