### ISSUE TITLE
[Git] Update git push command with  "Force push with lease" flag

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/ak-cli#210]
Update git push command [file](https://github.com/arshadkazmi42/ak-cli/blob/master/commands/git/git-push.md) with details about `--force-with-lease` flag

Ref: https://stackoverflow.com/a/52823955

**Comment by arimallick** [comment]
Please assign me this issue.

**Comment by arshadkazmi42** [comment]
@arimallick Assigned
