### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/ak-cli#39]
:memo:  Do you have a suggestion for this project.
Drop a comment here with your suggestion and let's discuss on how we can implement in this.

**Comment by arshadkazmi42** [comment]
Sounds good. Go ahead and create a PR

**Comment by arshadkazmi42** [comment]
@ryserCar Are you going to work on this?
I have also created a issue for this here #82

**Comment by ryserCar** [comment]
@arshadkazmi42 Yes, I just haven't found the time to clone the repo and work on it but will do it asap.

**Comment by sinumohan** [comment]
I would like to add PM2 and related commands also

**Comment by arshadkazmi42** [comment]
@sinumohan Sounds good. Go ahead.

**Comment by arshadkazmi42** [comment]
@sinumohan Created an issue for pm2 commands here #104
