### ISSUE TITLE
Change icons to images

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/ak-cli#49]
Currently in README.md we are using markdown icons for list items.
But in markdown we do not have much options. 
So we have decided to move on to images.
We need some icon images for the listed items in readme and needs to be updated in the README.md file

**Comment by arshadkazmi42** [comment]
Go ahead create a PR.
Basically, we are looking for some images which can be used in place of the markdown icons we are using. If you can find some free icons from opensource community, we can use those icons, which will be related to each commands category.

**Comment by Nelson-Chinedu** [comment]
@arshadkazmi42 it seems @mccarthydanielle has already sent a PR to the issue

**Comment by arshadkazmi42** [comment]
@Nelson-Chinedu Yes, but the images looks pixelated, we need some good images. If you have better images we can consider other options

**Comment by arshadkazmi42** [comment]
We have switched for markdown emoji for now.
