### ISSUE TITLE
Separate out Stage & Commit Command

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/ak-cli#72]
The below file,
https://github.com/arshadkazmi42/ak-cli/blob/master/commands/git/git-stage-commit.md
contains commands for `git add`, `git commit`, `git push`.
We want to separate it out for separate files. So it will be cleaner and easy to read.

**Comment by alpha-gamma** [comment]
Hi, I would like to work on it.

**Comment by arshadkazmi42** [comment]
@alpha-gamma Go ahead. Create a PR

**Comment by alpha-gamma** [comment]
Created the PR
